# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# Some Commands
alias py='python3'

alias pycharm='~/Documentos/pycharm-2022.1.1/bin/pycharm.sh'

alias discord='~/Documentos/discord/Discord/Discord'

alias bar='~/.config/polybar/panels/launch.sh'

alias poweroff='shutdown -h now'


#asdf
. "$HOME/.asdf/asdf.sh"


#Botoseis
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$PATH:$GEM_HOME/bin"


#go
export PATH="$PATH:/usr/local/go/bin"

#lvim
export PATH=/home/eduardo/.local/bin:$PATH

